import type { Comment, FriendRequest, Post, UserProfile } from '@/lib/types';

const HOUR = 1000 * 60 * 60;

function defaultModules(overrides?: Partial<Record<string, boolean>>) {
  return [
    { id: 'about' as const, visible: true, visibility: 'everyone' as const, order: 0 },
    { id: 'mood' as const, visible: true, visibility: 'everyone' as const, order: 1 },
    { id: 'topFriends' as const, visible: true, visibility: 'everyone' as const, order: 2 },
    { id: 'posts' as const, visible: true, visibility: 'everyone' as const, order: 3 },
  ].map((m) => ({ ...m, visible: overrides?.[m.id] ?? m.visible }));
}

export const ME_ID = 'me';

export function createSeedProfiles(now: number): Record<string, UserProfile> {
  return {
    me: {
      id: 'me',
      name: 'Avery Kim',
      handle: '@averykim',
      bio: 'Digital pack rat, always redecorating. Currently obsessed with reorganizing this exact page.',
      avatarColor: '#D9603B',
      wallpaper: 'cork',
      accentColor: '#D9603B',
      moodLabel: 'Chill',
      moodIcon: 'coffee',
      nowPlaying: 'Sunday Static — Field Notes',
      profileSongId: null,
      joinedLabel: `Joined ${new Date(now - 220 * 24 * HOUR).toLocaleString('en-US', { month: 'long', year: 'numeric' })}`,
      topFriendIds: ['u1', 'u2', 'u3'],
      friendCount: 3,
      modules: defaultModules(),
    },
    u1: {
      id: 'u1',
      name: 'Jules Marchetti',
      handle: '@julesm',
      bio: 'Bedroom producer. If the door is closed, there is a synth involved.',
      avatarColor: '#7B6BC9',
      wallpaper: 'midnight',
      accentColor: '#7B2FF7',
      moodLabel: 'Vibing',
      moodIcon: 'headphones',
      nowPlaying: 'Nocturnal Bloom — Cassette Dreams',
      profileSongId: null,
      joinedLabel: 'Joined March 2022',
      topFriendIds: ['me', 'u3'],
      friendCount: 2,
      modules: defaultModules(),
    },
    u2: {
      id: 'u2',
      name: 'Priya Anand',
      handle: '@priyawanders',
      bio: 'Slow travel, one duffel bag, zero regrets (mostly).',
      avatarColor: '#C9964A',
      wallpaper: 'sunset',
      accentColor: '#F2917A',
      moodLabel: 'Good day',
      moodIcon: 'sun',
      nowPlaying: null,
      profileSongId: null,
      joinedLabel: 'Joined June 2021',
      topFriendIds: ['me'],
      friendCount: 1,
      modules: defaultModules(),
    },
    u3: {
      id: 'u3',
      name: 'Theo Fischer',
      handle: '@theofish',
      bio: 'Cooking things low and slow. Ask me about cast iron, I will not stop talking.',
      avatarColor: '#4C7A6B',
      wallpaper: 'forest',
      accentColor: '#4C7A6B',
      moodLabel: 'Chill',
      moodIcon: 'coffee',
      nowPlaying: null,
      profileSongId: null,
      joinedLabel: 'Joined January 2023',
      topFriendIds: ['u1'],
      friendCount: 1,
      modules: defaultModules(),
    },
    u4: {
      id: 'u4',
      name: 'Nova Reyes',
      handle: '@novareyes',
      bio: 'Ranked grinder, semi-professional trash talker. Streams most nights.',
      avatarColor: '#B0455F',
      wallpaper: 'neon',
      accentColor: '#FF3D7F',
      moodLabel: 'Hype',
      moodIcon: 'zap',
      nowPlaying: null,
      profileSongId: null,
      joinedLabel: 'Joined October 2023',
      topFriendIds: [],
      friendCount: 0,
      modules: defaultModules(),
    },
    u5: {
      id: 'u5',
      name: 'Sam Okafor',
      handle: '@samokafor',
      bio: 'Shoots film, forgets to scan it for months. Low light is a personality trait.',
      avatarColor: '#3B5B7A',
      wallpaper: 'denim',
      accentColor: '#3B5B7A',
      moodLabel: 'Thoughtful',
      moodIcon: 'cloud',
      nowPlaying: null,
      profileSongId: null,
      joinedLabel: 'Joined May 2022',
      topFriendIds: [],
      friendCount: 0,
      modules: defaultModules(),
    },
    u6: {
      id: 'u6',
      name: 'Lena Kowalski',
      handle: '@lenak',
      bio: 'Writes poems about waiting rooms and other quietly unbearable places.',
      avatarColor: '#8E4A8C',
      wallpaper: 'pastel',
      accentColor: '#8E4A8C',
      moodLabel: 'In love',
      moodIcon: 'heart',
      nowPlaying: null,
      profileSongId: null,
      joinedLabel: 'Joined August 2023',
      topFriendIds: [],
      friendCount: 0,
      modules: defaultModules(),
    },
  };
}

const THUMBS = {
  music: require('@/assets/images/thumb-music.jpg'),
  travel: require('@/assets/images/thumb-travel.jpg'),
  cooking: require('@/assets/images/thumb-cooking.jpg'),
};

export function createSeedPosts(now: number): Post[] {
  const t = (hoursAgo: number) => now - hoursAgo * HOUR;
  return [
    {
      id: 'p1',
      authorId: 'me',
      kind: 'text',
      createdAt: t(0.5),
      likeCount: 12,
      commentCount: 3,
      likedByMe: false,
      text: 'Finally reorganized my whole page tonight. corkboard > any of these template feeds tbh',
      topics: ['lifestyle'],
    },
    {
      id: 'p2',
      authorId: 'u1',
      kind: 'reel',
      createdAt: t(1),
      likeCount: 341,
      commentCount: 22,
      likedByMe: false,
      caption: '3am chord experiments hit different',
      thumbnail: THUMBS.music,
      soundLabel: 'original sound — Jules Marchetti',
      viewsLabel: '12.4K',
      topics: ['music'],
    },
    {
      id: 'p3',
      authorId: 'u2',
      kind: 'video',
      createdAt: t(3),
      likeCount: 208,
      commentCount: 41,
      likedByMe: false,
      title: '48 Hours on the Amalfi Coast (no plan, no problem)',
      thumbnail: THUMBS.travel,
      durationLabel: '14:22',
      viewsLabel: '38K views',
      topics: ['travel'],
    },
    {
      id: 'p4',
      authorId: 'u3',
      kind: 'text',
      createdAt: t(5),
      likeCount: 34,
      commentCount: 6,
      likedByMe: true,
      text: 'Cast iron skillet finally seasoned right. Six months of babying it and worth every second.',
      topics: ['cooking'],
    },
    {
      id: 'p5',
      authorId: 'u1',
      kind: 'text',
      createdAt: t(8),
      likeCount: 8,
      commentCount: 1,
      likedByMe: false,
      text: 'If you need me I will be under a pile of cables and a broken synth.',
      topics: ['music'],
    },
    {
      id: 'p6',
      authorId: 'u4',
      kind: 'reel',
      createdAt: t(10),
      likeCount: 512,
      commentCount: 63,
      likedByMe: false,
      caption: 'clutch or fall back, no in between',
      thumbnail: THUMBS.music,
      soundLabel: 'original sound — Nova Reyes',
      viewsLabel: '22.1K',
      topics: ['gaming'],
    },
    {
      id: 'p7',
      authorId: 'u2',
      kind: 'text',
      createdAt: t(14),
      likeCount: 19,
      commentCount: 4,
      likedByMe: false,
      text: 'Packing list for slow travel: one backpack, two playlists, zero itinerary.',
      topics: ['travel'],
    },
    {
      id: 'p8',
      authorId: 'u5',
      kind: 'video',
      createdAt: t(18),
      likeCount: 96,
      commentCount: 12,
      likedByMe: false,
      title: 'Portraits in low light: gear + settings breakdown',
      thumbnail: THUMBS.music,
      durationLabel: '9:05',
      viewsLabel: '14K views',
      topics: ['photography'],
    },
    {
      id: 'p9',
      authorId: 'u6',
      kind: 'text',
      createdAt: t(22),
      likeCount: 27,
      commentCount: 9,
      likedByMe: false,
      text: 'Wrote a poem about waiting rooms. Turns out longing rhymes with almost everything.',
      topics: ['writing'],
    },
    {
      id: 'p10',
      authorId: 'u3',
      kind: 'reel',
      createdAt: t(26),
      likeCount: 188,
      commentCount: 15,
      likedByMe: false,
      caption: '6am prep, secret is in the browning',
      thumbnail: THUMBS.cooking,
      soundLabel: 'original sound — Theo Fischer',
      viewsLabel: '9.8K',
      topics: ['cooking'],
    },
    {
      id: 'p11',
      authorId: 'u6',
      kind: 'video',
      createdAt: t(30),
      likeCount: 61,
      commentCount: 7,
      likedByMe: false,
      title: 'Poetry reading: three unreleased pieces',
      thumbnail: THUMBS.travel,
      durationLabel: '6:40',
      viewsLabel: '5.2K views',
      topics: ['writing'],
    },
    {
      id: 'p12',
      authorId: 'me',
      kind: 'text',
      createdAt: t(34),
      likeCount: 5,
      commentCount: 2,
      likedByMe: false,
      text: 'Current mood: whatever the top-left corner of my profile is set to.',
      topics: ['lifestyle'],
    },
    {
      id: 'p13',
      authorId: 'u4',
      kind: 'text',
      createdAt: t(40),
      likeCount: 15,
      commentCount: 5,
      likedByMe: false,
      text: 'Ranked grind starts at midnight tonight, pulling up.',
      topics: ['gaming'],
    },
    {
      id: 'p14',
      authorId: 'u5',
      kind: 'text',
      createdAt: t(46),
      likeCount: 22,
      commentCount: 3,
      likedByMe: false,
      text: 'Sold my film scanner and immediately regretted it.',
      topics: ['photography'],
    },
  ];
}

export function createSeedComments(now: number): Comment[] {
  const t = (hoursAgo: number) => now - hoursAgo * HOUR;
  return [
    {
      id: 'c1',
      postId: 'p1',
      authorId: 'u1',
      text: 'It really does look better than any template feed, ngl.',
      createdAt: t(0.3),
    },
    {
      id: 'c2',
      postId: 'p1',
      authorId: 'u2',
      text: 'Okay the wallpaper choice is sending me',
      createdAt: t(0.2),
    },
    {
      id: 'c3',
      postId: 'p1',
      authorId: 'u3',
      text: 'Teach me your ways',
      createdAt: t(0.1),
    },
    {
      id: 'c4',
      postId: 'p2',
      authorId: 'me',
      text: 'This is the one, don\u2019t change a single note',
      createdAt: t(0.8),
    },
    {
      id: 'c5',
      postId: 'p2',
      authorId: 'u3',
      text: '3am is when the good ideas happen fr',
      createdAt: t(0.6),
    },
    {
      id: 'c6',
      postId: 'p3',
      authorId: 'u1',
      text: 'Adding this to the watch-later pile immediately',
      createdAt: t(2.5),
    },
    {
      id: 'c7',
      postId: 'p3',
      authorId: 'me',
      text: 'The no-plan energy is exactly why I clicked',
      createdAt: t(2),
    },
    {
      id: 'c8',
      postId: 'p4',
      authorId: 'u1',
      text: 'Six months of patience for one perfect skillet, respect',
      createdAt: t(4),
    },
  ];
}

export function createSeedFriendRequests(now: number): FriendRequest[] {
  return [
    { id: 'r1', fromUserId: 'u4', createdAt: now - 2 * HOUR },
    { id: 'r2', fromUserId: 'u6', createdAt: now - 20 * HOUR },
  ];
}

export const SEED_FRIEND_IDS = ['u1', 'u2', 'u3'];
